//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 17.06.2015 13:42:54
namespace TestDriver.TestSiteReference
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "TestData.Entities", "TestDriver.TestSiteReference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("TestDriver.TestSiteReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("TestData.Entities.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Patients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Patient> Patients
        {
            get
            {
                if ((this._Patients == null))
                {
                    this._Patients = base.CreateQuery<Patient>("Patients");
                }
                return this._Patients;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Patient> _Patients;
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Address> Addresses
        {
            get
            {
                if ((this._Addresses == null))
                {
                    this._Addresses = base.CreateQuery<Address>("Addresses");
                }
                return this._Addresses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Address> _Addresses;
        /// <summary>
        /// There are no comments for Associates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Associate> Associates
        {
            get
            {
                if ((this._Associates == null))
                {
                    this._Associates = base.CreateQuery<Associate>("Associates");
                }
                return this._Associates;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Associate> _Associates;
        /// <summary>
        /// There are no comments for PatientInsurances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PatientInsurance> PatientInsurances
        {
            get
            {
                if ((this._PatientInsurances == null))
                {
                    this._PatientInsurances = base.CreateQuery<PatientInsurance>("PatientInsurances");
                }
                return this._PatientInsurances;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PatientInsurance> _PatientInsurances;
        /// <summary>
        /// There are no comments for Patients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPatients(Patient patient)
        {
            base.AddObject("Patients", patient);
        }
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAddresses(Address address)
        {
            base.AddObject("Addresses", address);
        }
        /// <summary>
        /// There are no comments for Associates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAssociates(Associate associate)
        {
            base.AddObject("Associates", associate);
        }
        /// <summary>
        /// There are no comments for PatientInsurances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPatientInsurances(PatientInsurance patientInsurance)
        {
            base.AddObject("PatientInsurances", patientInsurance);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"TestData.Entities\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/ed" +
                "m\"><EntityType Name=\"Patient\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name" +
                "=\"FirstName\" Type=\"Edm.String\" /><Property Name=\"LastName\" Type=\"Edm.String\" /><" +
                "Property Name=\"AddressId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"As" +
                "sociateId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><NavigationProperty Name=\"Address\" Relationship=\"TestData" +
                ".Entities.TestData_Entities_Patient_Address_TestData_Entities_Address_AddressPar" +
                "tner\" ToRole=\"Address\" FromRole=\"AddressPartner\" /><NavigationProperty Name=\"Ass" +
                "ociate\" Relationship=\"TestData.Entities.TestData_Entities_Patient_Associate_Test" +
                "Data_Entities_Associate_AssociatePartner\" ToRole=\"Associate\" FromRole=\"Associate" +
                "Partner\" /><NavigationProperty Name=\"PatientInsurances\" Relationship=\"TestData.E" +
                "ntities.TestData_Entities_Patient_PatientInsurances_TestData_Entities_PatientIns" +
                "urance_PatientInsurancesPartner\" ToRole=\"PatientInsurances\" FromRole=\"PatientIns" +
                "urancesPartner\" /></EntityType><EntityType Name=\"Address\"><Key><PropertyRef Name" +
                "=\"Id\" /></Key><Property Name=\"Street\" Type=\"Edm.String\" /><Property Name=\"Zip\" T" +
                "ype=\"Edm.String\" /><Property Name=\"City\" Type=\"Edm.String\" /><Property Name=\"Cou" +
                "ntry\" Type=\"Edm.String\" /><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" " +
                "/></EntityType><EntityType Name=\"Associate\"><Key><PropertyRef Name=\"Id\" /></Key>" +
                "<Property Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Role\" Type=\"Edm.String" +
                "\" /><Property Name=\"AddressId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Nam" +
                "e=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Address\" Re" +
                "lationship=\"TestData.Entities.TestData_Entities_Associate_Address_TestData_Entit" +
                "ies_Address_AddressPartner\" ToRole=\"Address\" FromRole=\"AddressPartner\" /></Entit" +
                "yType><EntityType Name=\"PatientInsurance\"><Key><PropertyRef Name=\"Id\" /></Key><P" +
                "roperty Name=\"InsuranceNumber\" Type=\"Edm.String\" /><Property Name=\"PatientId\" Ty" +
                "pe=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"InsuranceId\" Type=\"Edm.Int32\" " +
                "Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Navi" +
                "gationProperty Name=\"Patient\" Relationship=\"TestData.Entities.TestData_Entities_" +
                "PatientInsurance_Patient_TestData_Entities_Patient_PatientPartner\" ToRole=\"Patie" +
                "nt\" FromRole=\"PatientPartner\" /><NavigationProperty Name=\"Insurance\" Relationshi" +
                "p=\"TestData.Entities.TestData_Entities_PatientInsurance_Insurance_TestData_Entit" +
                "ies_Insurance_InsurancePartner\" ToRole=\"Insurance\" FromRole=\"InsurancePartner\" /" +
                "></EntityType><EntityType Name=\"Insurance\"><Key><PropertyRef Name=\"Id\" /></Key><" +
                "Property Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Type\" Type=\"Edm.String\"" +
                " /><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /></EntityType><Associa" +
                "tion Name=\"TestData_Entities_Patient_Address_TestData_Entities_Address_AddressPa" +
                "rtner\"><End Type=\"TestData.Entities.Address\" Role=\"Address\" Multiplicity=\"0..1\" " +
                "/><End Type=\"TestData.Entities.Patient\" Role=\"AddressPartner\" Multiplicity=\"0..1" +
                "\" /></Association><Association Name=\"TestData_Entities_Patient_Associate_TestDat" +
                "a_Entities_Associate_AssociatePartner\"><End Type=\"TestData.Entities.Associate\" R" +
                "ole=\"Associate\" Multiplicity=\"0..1\" /><End Type=\"TestData.Entities.Patient\" Role" +
                "=\"AssociatePartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"TestD" +
                "ata_Entities_Patient_PatientInsurances_TestData_Entities_PatientInsurance_Patien" +
                "tInsurancesPartner\"><End Type=\"TestData.Entities.PatientInsurance\" Role=\"Patient" +
                "Insurances\" Multiplicity=\"*\" /><End Type=\"TestData.Entities.Patient\" Role=\"Patie" +
                "ntInsurancesPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"Test" +
                "Data_Entities_Associate_Address_TestData_Entities_Address_AddressPartner\"><End T" +
                "ype=\"TestData.Entities.Address\" Role=\"Address\" Multiplicity=\"0..1\" /><End Type=\"" +
                "TestData.Entities.Associate\" Role=\"AddressPartner\" Multiplicity=\"0..1\" /></Assoc" +
                "iation><Association Name=\"TestData_Entities_PatientInsurance_Patient_TestData_En" +
                "tities_Patient_PatientPartner\"><End Type=\"TestData.Entities.Patient\" Role=\"Patie" +
                "nt\" Multiplicity=\"0..1\" /><End Type=\"TestData.Entities.PatientInsurance\" Role=\"P" +
                "atientPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"TestData_E" +
                "ntities_PatientInsurance_Insurance_TestData_Entities_Insurance_InsurancePartner\"" +
                "><End Type=\"TestData.Entities.Insurance\" Role=\"Insurance\" Multiplicity=\"0..1\" />" +
                "<End Type=\"TestData.Entities.PatientInsurance\" Role=\"InsurancePartner\" Multiplic" +
                "ity=\"0..1\" /></Association></Schema><Schema Namespace=\"Default\" xmlns=\"http://sc" +
                "hemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Container\" m:IsDefau" +
                "ltEntityContainer=\"true\"><EntitySet Name=\"Patients\" EntityType=\"TestData.Entitie" +
                "s.Patient\" /><EntitySet Name=\"Addresses\" EntityType=\"TestData.Entities.Address\" " +
                "/><EntitySet Name=\"Associates\" EntityType=\"TestData.Entities.Associate\" /><Entit" +
                "ySet Name=\"PatientInsurances\" EntityType=\"TestData.Entities.PatientInsurance\" />" +
                "<AssociationSet Name=\"TestData_Entities_Patient_Address_TestData_Entities_Addres" +
                "s_AddressPartnerSet\" Association=\"TestData.Entities.TestData_Entities_Patient_Ad" +
                "dress_TestData_Entities_Address_AddressPartner\"><End Role=\"AddressPartner\" Entit" +
                "ySet=\"Patients\" /><End Role=\"Address\" EntitySet=\"Addresses\" /></AssociationSet><" +
                "AssociationSet Name=\"TestData_Entities_Patient_Associate_TestData_Entities_Assoc" +
                "iate_AssociatePartnerSet\" Association=\"TestData.Entities.TestData_Entities_Patie" +
                "nt_Associate_TestData_Entities_Associate_AssociatePartner\"><End Role=\"AssociateP" +
                "artner\" EntitySet=\"Patients\" /><End Role=\"Associate\" EntitySet=\"Associates\" /></" +
                "AssociationSet><AssociationSet Name=\"TestData_Entities_Patient_PatientInsurances" +
                "_TestData_Entities_PatientInsurance_PatientInsurancesPartnerSet\" Association=\"Te" +
                "stData.Entities.TestData_Entities_Patient_PatientInsurances_TestData_Entities_Pa" +
                "tientInsurance_PatientInsurancesPartner\"><End Role=\"PatientInsurancesPartner\" En" +
                "titySet=\"Patients\" /><End Role=\"PatientInsurances\" EntitySet=\"PatientInsurances\"" +
                " /></AssociationSet><AssociationSet Name=\"TestData_Entities_Associate_Address_Te" +
                "stData_Entities_Address_AddressPartnerSet\" Association=\"TestData.Entities.TestDa" +
                "ta_Entities_Associate_Address_TestData_Entities_Address_AddressPartner\"><End Rol" +
                "e=\"AddressPartner\" EntitySet=\"Associates\" /><End Role=\"Address\" EntitySet=\"Addre" +
                "sses\" /></AssociationSet><AssociationSet Name=\"TestData_Entities_PatientInsuranc" +
                "e_Patient_TestData_Entities_Patient_PatientPartnerSet\" Association=\"TestData.Ent" +
                "ities.TestData_Entities_PatientInsurance_Patient_TestData_Entities_Patient_Patie" +
                "ntPartner\"><End Role=\"PatientPartner\" EntitySet=\"PatientInsurances\" /><End Role=" +
                "\"Patient\" EntitySet=\"Patients\" /></AssociationSet></EntityContainer></Schema></e" +
                "dmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for TestData.Entities.Patient in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Patients")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Patient : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="addressId">Initial value of AddressId.</param>
        /// <param name="associateId">Initial value of AssociateId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Patient CreatePatient(int addressId, int associateId, int ID)
        {
            Patient patient = new Patient();
            patient.AddressId = addressId;
            patient.AssociateId = associateId;
            patient.Id = ID;
            return patient;
        }
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property AddressId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AddressId
        {
            get
            {
                return this._AddressId;
            }
            set
            {
                this.OnAddressIdChanging(value);
                this._AddressId = value;
                this.OnAddressIdChanged();
                this.OnPropertyChanged("AddressId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AddressId;
        partial void OnAddressIdChanging(int value);
        partial void OnAddressIdChanged();
        /// <summary>
        /// There are no comments for Property AssociateId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AssociateId
        {
            get
            {
                return this._AssociateId;
            }
            set
            {
                this.OnAssociateIdChanging(value);
                this._AssociateId = value;
                this.OnAssociateIdChanged();
                this.OnPropertyChanged("AssociateId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AssociateId;
        partial void OnAssociateIdChanging(int value);
        partial void OnAssociateIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Address Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Address _Address;
        /// <summary>
        /// There are no comments for Associate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Associate Associate
        {
            get
            {
                return this._Associate;
            }
            set
            {
                this._Associate = value;
                this.OnPropertyChanged("Associate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Associate _Associate;
        /// <summary>
        /// There are no comments for PatientInsurances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<PatientInsurance> PatientInsurances
        {
            get
            {
                return this._PatientInsurances;
            }
            set
            {
                this._PatientInsurances = value;
                this.OnPropertyChanged("PatientInsurances");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<PatientInsurance> _PatientInsurances = new global::System.Data.Services.Client.DataServiceCollection<PatientInsurance>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TestData.Entities.Address in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Addresses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Address : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Address CreateAddress(int ID)
        {
            Address address = new Address();
            address.Id = ID;
            return address;
        }
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
                this.OnPropertyChanged("Street");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property Zip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this.OnZipChanging(value);
                this._Zip = value;
                this.OnZipChanged();
                this.OnPropertyChanged("Zip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Zip;
        partial void OnZipChanging(string value);
        partial void OnZipChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TestData.Entities.Associate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Associates")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Associate : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Associate object.
        /// </summary>
        /// <param name="addressId">Initial value of AddressId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Associate CreateAssociate(int addressId, int ID)
        {
            Associate associate = new Associate();
            associate.AddressId = addressId;
            associate.Id = ID;
            return associate;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Role in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Role
        {
            get
            {
                return this._Role;
            }
            set
            {
                this.OnRoleChanging(value);
                this._Role = value;
                this.OnRoleChanged();
                this.OnPropertyChanged("Role");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Role;
        partial void OnRoleChanging(string value);
        partial void OnRoleChanged();
        /// <summary>
        /// There are no comments for Property AddressId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AddressId
        {
            get
            {
                return this._AddressId;
            }
            set
            {
                this.OnAddressIdChanging(value);
                this._AddressId = value;
                this.OnAddressIdChanged();
                this.OnPropertyChanged("AddressId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AddressId;
        partial void OnAddressIdChanging(int value);
        partial void OnAddressIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Address Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Address _Address;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TestData.Entities.PatientInsurance in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PatientInsurances")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PatientInsurance : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PatientInsurance object.
        /// </summary>
        /// <param name="patientId">Initial value of PatientId.</param>
        /// <param name="insuranceId">Initial value of InsuranceId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PatientInsurance CreatePatientInsurance(int patientId, int insuranceId, int ID)
        {
            PatientInsurance patientInsurance = new PatientInsurance();
            patientInsurance.PatientId = patientId;
            patientInsurance.InsuranceId = insuranceId;
            patientInsurance.Id = ID;
            return patientInsurance;
        }
        /// <summary>
        /// There are no comments for Property InsuranceNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InsuranceNumber
        {
            get
            {
                return this._InsuranceNumber;
            }
            set
            {
                this.OnInsuranceNumberChanging(value);
                this._InsuranceNumber = value;
                this.OnInsuranceNumberChanged();
                this.OnPropertyChanged("InsuranceNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InsuranceNumber;
        partial void OnInsuranceNumberChanging(string value);
        partial void OnInsuranceNumberChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this._PatientId = value;
                this.OnPatientIdChanged();
                this.OnPropertyChanged("PatientId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PatientId;
        partial void OnPatientIdChanging(int value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Property InsuranceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int InsuranceId
        {
            get
            {
                return this._InsuranceId;
            }
            set
            {
                this.OnInsuranceIdChanging(value);
                this._InsuranceId = value;
                this.OnInsuranceIdChanged();
                this.OnPropertyChanged("InsuranceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _InsuranceId;
        partial void OnInsuranceIdChanging(int value);
        partial void OnInsuranceIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                return this._Patient;
            }
            set
            {
                this._Patient = value;
                this.OnPropertyChanged("Patient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
        /// <summary>
        /// There are no comments for Insurance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Insurance Insurance
        {
            get
            {
                return this._Insurance;
            }
            set
            {
                this._Insurance = value;
                this.OnPropertyChanged("Insurance");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Insurance _Insurance;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TestData.Entities.Insurance in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Insurance : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Insurance object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Insurance CreateInsurance(int ID)
        {
            Insurance insurance = new Insurance();
            insurance.Id = ID;
            return insurance;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
